### ISSUE TITLE
`getProductList` transition duplicates items while searching for exact product id

### ISSUE THREAD

**Issue by diegonc** [moqui/SimpleScreens#138]
### Steps to Reproduce

1. Go to [https://demo.moqui.org/qapps/PopcAdmin/Asset/Asset/FindAsset](https://demo.moqui.org/qapps/PopcAdmin/Asset/Asset/FindAsset)
2. Click `Find Options` button
3. In Product combo-box enter `DEMO_1_1`

### Results

The product with ID `DEMO_1_1` is listed twice as is shown in the following screenshot.

![image](https://github.com/moqui/SimpleScreens/assets/261458/2e9c44d1-55e2-45fd-9740-833366cb1a1c)

### Causes

My suspicion is that the `getProductList` transition adds one instance of the `DEMO_1_1` product while looking up by id in line below

https://github.com/moqui/SimpleScreens/blob/master/template/product/ProductTransitions.xml#L38

and then when searching through ElasticSearch another instance is added in the loop below

https://github.com/moqui/SimpleScreens/blob/master/template/product/ProductTransitions.xml#L106

**Comment by jonesde** [comment]
This is intentional behavior, maybe confusing to users, but the design is as you describe and it isn't just a quirk in implementation: if there is an exact ID match then it is always the first item in the list, and other search results are independent of that (which usually means you know it was an exact ID match if the next item in the list, or soon after it, is the same product). Part of the UI design problem is there is not currently any way, especially from the server side, to highlight an item as being different from the others. Before this design, IIRC, it used to only show the exact match if there was an exact match, then it was changed to this approach.

**Comment by diegonc** [comment]
Ok, thanks for the rationale.
